# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeBuildPipeline' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeBuildPipeline

  

  platform :ios, '9.0'
  target 'ReactNativeBuildPipelineTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeBuildPipeline-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeBuildPipeline-tvOS

  target 'ReactNativeBuildPipeline-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
